### PR TITLE
FD-66: Add home page carousel

### PR DESCRIPTION
**Pull request by rwilkinson3**

### CODE REVIEW

**Review by msherry2 — CHANGES_REQUESTED** [review]
This is really good for the most part!
A couple comments:

- With regards to the JavaScript - the code for the existing carousel (and most of the rest of the site) is in `assets/js/app.js` and I think you could just modify that file directly. You may be able to reuse some of the screen breakpoints.
- The mobile layout of the cards still needs work, but I'm guessing that is on your radar anyway.
- There is supposed to be the black callout box on the left side with a short blurb about each game. Please add that in as part of this ticket.
- We showed this version to FD. Mentioned the `>` is misleading so Eric may update that asset in Figma, but they want the functionality to remain the same (no forward/back buttons). Also mentioned a11y concerns, particularly keyboard navigation and a way to pause all movement (video play and carousel auto advance) and they agreed we should implement that. Eric will probably provide guidance on the pause icon and placement.

**Comment by rwilkinson3** [comment]
- Inline JS moved to `app.js`
- Many positioning tweaks with carousel
- Info box added with logo.
- I didn't address the chevron graphic or pausing in the carousel.

**Review by msherry2 — CHANGES_REQUESTED** [review]
A few comments, mainly with regards to the mobile screen size:
- I think the `.thumb-caption` font size shouldn't go lower than 14px (with line-height 16px) - it just gets too small imo. 
- I think `.carousel-indicators li` width can be set to 23%. This still fits on the smallest devices, but lets them expand on larger mobile screens up until you hit the 664px breakpoint for tablets. This also helps with the larger font size mentioned above.
- If you go with the percentage for the `carousel li` element above, then the `img` can be set to 100% to fill the available space, again, until the 664 breakpoint.

**Comment by rwilkinson3** [comment]
Recommendations have been implemented. I agree the minimum 14 font-size looks much better, I was using 11 because the Figma mockup dropped to that for the iPhone mini.

**Review by msherry2 — APPROVED** [review]
Thanks Ryan!

**Pull request merged**
