### PR TITLE
FD-74 Odds and ends

### PR DESCRIPTION
**Pull request by msherry2**
- Fix Google font “Fraunces” on Mac
- +10% hover on Bios images and carousel 
- Change Teacher Fellowships to Fellowships in mobile nav
- Comment out Get Involved buttons
- Add reveal effect to spotlight
- Rename redesign.php to index.php
- CSS cleanup and minor layout tweaks to helm, cabin, and modeling-room
- Removed CI script for `release/home-redesign` branch

### CODE REVIEW

**Review by jwisc — CHANGES_REQUESTED** [review]
- [ ]     Fix Google font “Fraunces” on Mac
_Do the snippets related to 'brandon-grotesque' address the issue? I don't see any explicit changes to the way the font is embedded. 
Also, were you able to test this on iOS? I cannot test Safari on this machine._

- [ ]     +10% hover on Bios images and carousel
_For the carousel, the card stays magnified while it is the actively selected card, but this is not the case for the Bio section. I think either way is fine, I just wanted to point this out in case you would prefer to have the same behavior in the Bio section._
- [x]     Change Teacher Fellowships to Fellowships in mobile nav
- [x]     Comment out Get Involved buttons
- [x]     Add reveal effect to spotlight
- [x]     Rename redesign.php to index.php
- [ ]     CSS cleanup and minor layout tweaks to helm, cabin, and modeling-room
_There is a screen size range (widths 1070px through 1161px) where the film reel in "Games as assessment" jumps out of place_

- [x]     Removed CI script for release/home-redesign branch

### additional notes:
- It doesn't appear that the carousel or bio cards are keyboard-navigable

**Comment by msherry2** [comment]
- fix "Fraunces" on Mac - Adding `font-style: italic;` fixed the problem. I did test this on a Mac.
- +10% hover - In the bios section, there is already a selected indicator (down arrow under selected image) and the mockup didn't show the +10% for the selected person, so I don't think it is needed in that section.
- I fixed the modeling-reel issue, thanks for catching that!
- The bio cards use js `gridder` library and it wasn't built with accessibility in mind (from 2015). It isn't keyboard accessible out of the box so I'd need to dig into the source code. It is used elsewhere throughout the site so I didn't bring in a more modern solution. We did specifically ask them about keyboard nav on the carousel and they said they didn't want it. I brought up a few other a11y concerns during an earlier meeting (lots of motion on this page that the user can't pause for example). I think/hope some of that will be addressed in a future update. They were responsive to the suggestions.

**Comment by jwisc** [comment]
image
The mockup (pictured here) does appear to show the magnification on the selected card, though it is unclear whether or not this magnification only represents the hover behavior. Either way, there is already a selected indicator as you mentioned.

**Comment by msherry2** [comment]
You're right! I'll fix that.

**Comment by jwisc** [comment]
image

- upon scrolling past the 'Games are where the kids are' section, the spotlight used in the deepsea section suddenly appears and is visible in the background before a user scrolls to the section where it is intended to be seen (see image)
- this happens at a variety of screen sizes from mobile to extra large

**Comment by msherry2** [comment]
Spent a while looking for an alternate solution, but this one works. I'm out Monday, so if you approve the PR, could you merge it in for me? Thanks June!

**Pull request merged**
